import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} className='scroll-smooth  scrollbar-thumb-gray-900 scrollbar-track-gray-100 scrollbar-thin'>{children}</body>
    </html>
  )
}
