'use client'


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { PositionalAudio } from "@react-three/drei";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ShahriyarModel(props) {
    const { nodes, materials } = useGLTF("/thisistheend.glb")


    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Wall001.geometry}
                material={materials["Walls.003"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015.geometry}
                material={materials["Sealing Lights 2"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_3002.geometry}
                material={materials["Material.006"]}
                position={[-15.147, 1.23, -9.017]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
                scale={[1.31, 1.31, 1.704]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2001.geometry}
                material={materials["SBWORKING_Material.010"]}
                position={[-17.634, 1.366, -11.274]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.737, 1.737, 2.07]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5.geometry}
                material={materials["Material.011"]}
                position={[-12.838, 1.194, -9.274]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.737}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_4.geometry}
                material={materials["Material.008"]}
                position={[-12.838, 1.194, -11.603]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.737}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Middle_Stand.geometry}
                material={materials["Walls.001"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Wall.geometry}
                material={materials.Walls}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Door.geometry}
                material={materials.wire_115115115}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2059.geometry}
                material={materials["Material.009"]}
                position={[-17.634, 1.366, -13.274]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.737, 1.737, 2.07]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ABOUTHIM001.geometry}
                material={materials["ABOUTHIM.001"]}
                position={[-3.246, 2.911, -3.759]}
                rotation={[Math.PI / 2, 0, 0.781]}
                scale={3.663}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Middle_Stand001.geometry}
                material={materials["Walls.006"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text009.geometry}
                material={materials["Dark Writing"]}
                position={[-1.111, 4.77, 1.218]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.369}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004.geometry}
                material={materials["Material.007"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003.geometry}
                material={materials["Glass.001"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text002.geometry}
                material={materials["BackDrop.008"]}
                position={[-2.213, 1.924, -1.819]}
                rotation={[1.144, -0.801, 0.973]}
                scale={0.325}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1004.geometry}
                material={materials["Allah (1) - 2018"]}
                position={[-14.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2.geometry}
                material={materials["Allah (1) - 2018.021"]}
                position={[-12.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_3001.geometry}
                material={materials["Allah (1) - 2018.022"]}
                position={[-10.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_4001.geometry}
                material={materials["Allah (1) - 2018.023"]}
                position={[-8.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5001.geometry}
                material={materials["Allah (1) - 2018.024"]}
                position={[-6.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_7.geometry}
                material={materials["Allah (1) - 2018.025"]}
                position={[-2.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_6001.geometry}
                material={materials["Allah (1) - 2018.026"]}
                position={[-4.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_8.geometry}
                material={materials["Allah (1) - 2018.027"]}
                position={[-0.815, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_9.geometry}
                material={materials["Allah (1) - 2018.028"]}
                position={[1.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_10.geometry}
                material={materials["Allah (1) - 2018.029"]}
                position={[3.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_11.geometry}
                material={materials["Allah (1) - 2018.030"]}
                position={[5.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_12.geometry}
                material={materials["Allah (1) - 2018.031"]}
                position={[7.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_13.geometry}
                material={materials["Allah (1) - 2018.032"]}
                position={[9.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_14.geometry}
                material={materials["Allah (1) - 2018.033"]}
                position={[11.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_15.geometry}
                material={materials["Allah (1) - 2018.034"]}
                position={[13.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_16.geometry}
                material={materials["Allah (1) - 2018.035"]}
                position={[15.185, 1.459, 17.571]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall.geometry}
                material={materials["Walls.002"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1002.geometry}
                material={materials["1. Allah - 2021"]}
                position={[-7.189, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1003.geometry}
                material={materials["1. Allah - 2021.012"]}
                position={[-4.189, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_3.geometry}
                material={materials["1. Allah - 2021.013"]}
                position={[-1.189, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_4002.geometry}
                material={materials["1. Allah - 2021.014"]}
                position={[1.811, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5002.geometry}
                material={materials["1. Allah - 2021.015"]}
                position={[4.811, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_6.geometry}
                material={materials["1. Allah - 2021.016"]}
                position={[7.811, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5003.geometry}
                material={materials["1. Allah - 2021.017"]}
                position={[10.811, 1.604, 11.216]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.644}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5004.geometry}
                material={materials["1. Allah - 2021.018"]}
                position={[17.581, 3.825, 15.629]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.715}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5005.geometry}
                material={materials["1. Allah - 2021.019"]}
                position={[17.581, 1.825, 15.629]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.715}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5006.geometry}
                material={materials["1. Allah - 2021.020"]}
                position={[17.581, 1.825, 12.629]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.715}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_5007.geometry}
                material={materials["1. Allah - 2021.021"]}
                position={[17.581, 3.825, 12.629]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.715}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Main_Text.geometry}
                material={materials["Material.001"]}
                position={[8.995, 4.578, 17.064]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={0.668}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                material={materials["Material.007"]}
                position={[-16.638, 0.745, 17.18]}
                rotation={[-Math.PI, 1.52, -Math.PI]}
                scale={0.599}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002.geometry}
                material={materials["Glass.002"]}
                position={[-16.625, 1.583, 17.215]}
                rotation={[0, -1.52, 0.693]}
                scale={[-0.406, -0.017, -0.406]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text001.geometry}
                material={materials["BackDrop.001"]}
                position={[-16.612, 1.578, 17.144]}
                rotation={[2.456, -0.005, 3.104]}
                scale={0.284}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1.geometry}
                material={materials["Allah (1) - 2018.036"]}
                position={[17.573, 1.551, 5.262]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2002.geometry}
                material={materials["Allah (1) - 2018.037"]}
                position={[17.573, 1.551, 3.762]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2003.geometry}
                material={materials["Allah (1) - 2018.038"]}
                position={[17.573, 1.551, 2.262]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2004.geometry}
                material={materials["Allah (1) - 2018.039"]}
                position={[17.573, 1.551, -2.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2005.geometry}
                material={materials["Allah (1) - 2018.040"]}
                position={[17.573, 1.551, -0.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1005.geometry}
                material={materials["Allah (1) - 2018.041"]}
                position={[17.573, 1.551, 0.762]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2006.geometry}
                material={materials["Allah (1) - 2018.042"]}
                position={[17.573, 1.551, -9.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2007.geometry}
                material={materials["Allah (1) - 2018.043"]}
                position={[17.573, 1.551, -11.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2008.geometry}
                material={materials["Allah (1) - 2018.044"]}
                position={[17.573, 1.551, -6.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2009.geometry}
                material={materials["Allah (1) - 2018.045"]}
                position={[17.573, 1.551, -5.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1006.geometry}
                material={materials["Allah (1) - 2018.046"]}
                position={[17.573, 1.551, -8.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1007.geometry}
                material={materials["Allah (1) - 2018.047"]}
                position={[17.573, 1.551, -3.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2010.geometry}
                material={materials["Allah (1) - 2018.048"]}
                position={[17.573, 1.551, -6.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2011.geometry}
                material={materials["Allah (1) - 2018.049"]}
                position={[17.573, 1.551, -11.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2012.geometry}
                material={materials["Allah (1) - 2018.050"]}
                position={[17.573, 1.551, -9.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1008.geometry}
                material={materials["Allah (1) - 2018.051"]}
                position={[17.573, 1.551, -8.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2013.geometry}
                material={materials["Allah (1) - 2018.052"]}
                position={[17.573, 1.551, -15.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2015.geometry}
                material={materials["Allah (1) - 2018.054"]}
                position={[17.573, 1.551, -12.738]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1009.geometry}
                material={materials["Allah (1) - 2018.055"]}
                position={[17.573, 1.551, -14.238]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder006.geometry}
                material={materials["Material.007"]}
                position={[13.987, 0.745, 10.177]}
                rotation={[0, -0.798, 0]}
                scale={0.599}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder005.geometry}
                material={materials["Glass.003"]}
                position={[13.955, 1.583, 10.16]}
                rotation={[Math.PI, 0.798, -2.449]}
                scale={[-0.406, -0.017, -0.406]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text003.geometry}
                material={materials["BackDrop.002"]}
                position={[13.962, 1.63, 10.156]}
                rotation={[0.831, 0.541, -0.547]}
                scale={0.284}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1010.geometry}
                material={materials["Allah (1) - 2018.069"]}
                position={[-2.996, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[0.917, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1011.geometry}
                material={materials["Allah (1) - 2018.070"]}
                position={[-8.996, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1012.geometry}
                material={materials["Allah (1) - 2018.071"]}
                position={[7.56, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1014.geometry}
                material={materials["Allah (1) - 2018.073"]}
                position={[12.06, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1015.geometry}
                material={materials["Allah (1) - 2018.074"]}
                position={[16.56, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2014.geometry}
                material={materials["Allah (1) - 2018.056"]}
                position={[-4.496, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2016.geometry}
                material={materials["Allah (1) - 2018.057"]}
                position={[-1.496, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.311, 1.311, 1.849]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2017.geometry}
                material={materials["Allah (1) - 2018.058"]}
                position={[-7.496, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2018.geometry}
                material={materials["Allah (1) - 2018.059"]}
                position={[-5.996, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2019.geometry}
                material={materials["Allah (1) - 2018.060"]}
                position={[4.56, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2020.geometry}
                material={materials["Allah (1) - 2018.061"]}
                position={[6.06, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2021.geometry}
                material={materials["Allah (1) - 2018.062"]}
                position={[4.56, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2024.geometry}
                material={materials["Allah (1) - 2018.065"]}
                position={[10.56, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2025.geometry}
                material={materials["Allah (1) - 2018.066"]}
                position={[9.06, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2026.geometry}
                material={materials["Allah (1) - 2018.067"]}
                position={[13.56, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2027.geometry}
                material={materials["Allah (1) - 2018.068"]}
                position={[15.06, 1.551, -17.411]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.molana.geometry}
                material={materials.molana}
                position={[17.594, 3.159, 8.173]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={2.469}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text.geometry}
                material={materials["Material.001"]}
                position={[17.599, 3.727, 4.233]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall001.geometry}
                material={materials["Walls.004"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall002.geometry}
                material={materials["Walls.005"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text004.geometry}
                material={materials["Material.002"]}
                position={[-2.54, 2.727, -12.656]}
                rotation={[Math.PI / 2, 0, Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2023.geometry}
                material={materials["Allah (1) - 2018.076"]}
                position={[0.004, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[0.97, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1013.geometry}
                material={materials["Allah (1) - 2018.077"]}
                position={[1.804, 1.551, -12.548]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.704, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text005.geometry}
                material={materials["BackDrop.003"]}
                position={[-8.626, 1.578, 10.142]}
                rotation={[2.42, -0.29, 2.862]}
                scale={0.249}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder007.geometry}
                material={materials["Glass.004"]}
                position={[-8.612, 1.583, 10.213]}
                rotation={[0, -1.148, 0.693]}
                scale={[-0.406, -0.017, -0.406]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder008.geometry}
                material={materials["Material.007"]}
                position={[-8.636, 0.745, 10.185]}
                rotation={[-Math.PI, 1.148, -Math.PI]}
                scale={0.599}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text006.geometry}
                material={materials["Material.003"]}
                position={[13.52, 2.839, 0.798]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2022.geometry}
                material={materials["Allah (1) - 2018.078"]}
                position={[13.547, 1.551, 5.649]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2028.geometry}
                material={materials["Allah (1) - 2018.079"]}
                position={[13.547, 1.551, 9.087]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2029.geometry}
                material={materials["Allah (1) - 2018.080"]}
                position={[13.547, 1.551, 2.211]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2031.geometry}
                material={materials["Allah (1) - 2018.082"]}
                position={[13.547, 1.551, -1.227]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2032.geometry}
                material={materials["Allah (1) - 2018.083"]}
                position={[13.547, 1.551, -2.946]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2036.geometry}
                material={materials["Allah (1) - 2018.087"]}
                position={[13.547, 1.551, -8.103]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2037.geometry}
                material={materials["Allah (1) - 2018.088"]}
                position={[13.547, 1.551, -6.384]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2038.geometry}
                material={materials["Allah (1) - 2018.089"]}
                position={[13.547, 1.551, -11.542]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1016.geometry}
                material={materials["Allah (1) - 2018.091"]}
                position={[13.547, 1.551, 7.368]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1017.geometry}
                material={materials["Allah (1) - 2018.092"]}
                position={[13.547, 1.551, 0.492]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1018.geometry}
                material={materials["Allah (1) - 2018.093"]}
                position={[13.547, 1.551, -4.665]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_1020.geometry}
                material={materials["Allah (1) - 2018.095"]}
                position={[13.547, 1.551, -9.823]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2030.geometry}
                material={materials["Allah (1) - 2018.097"]}
                position={[13.547, 1.551, 3.935]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2033.geometry}
                material={materials["Allah (1) - 2018.098"]}
                position={[12.203, 1.551, -12.53]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
                scale={[1.502, 1.311, 1.311]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2034.geometry}
                material={materials["Allah (1) - 2018.099"]}
                position={[10.203, 1.551, -12.53]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
                scale={[1.298, 1.731, 1.731]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2035.geometry}
                material={materials["Allah (1) - 2018.100"]}
                position={[8.203, 1.551, -12.53]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
                scale={[1.256, 1.704, 1.704]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2039.geometry}
                material={materials["Allah (1) - 2018.101"]}
                position={[6.203, 1.551, -12.53]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
                scale={[0.969, 1.709, 1.709]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2041.geometry}
                material={materials["Allah (1) - 2018.109"]}
                position={[-6.815, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2040.geometry}
                material={materials["Allah (1) - 2018.110"]}
                position={[-4.815, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2042.geometry}
                material={materials["Allah (1) - 2018.111"]}
                position={[-2.815, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2043.geometry}
                material={materials["Allah (1) - 2018.112"]}
                position={[-0.815, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2044.geometry}
                material={materials["Allah (1) - 2018.113"]}
                position={[1.185, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2045.geometry}
                material={materials["Allah (1) - 2018.114"]}
                position={[3.185, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2046.geometry}
                material={materials["Allah (1) - 2018.115"]}
                position={[5.185, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2047.geometry}
                material={materials["Allah (1) - 2018.116"]}
                position={[7.185, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2048.geometry}
                material={materials["Allah (1) - 2018.117"]}
                position={[9.185, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2049.geometry}
                material={materials["Allah (1) - 2018.118"]}
                position={[11.185, 1.459, 10.894]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text007.geometry}
                material={materials["Material.004"]}
                position={[5.599, 2.699, 10.925]}
                rotation={[Math.PI / 2, 0, Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2050.geometry}
                material={materials["Allah (1) - 2018.119"]}
                position={[13.185, 1.459, 8.894]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2051.geometry}
                material={materials["Allah (1) - 2018.120"]}
                position={[13.185, 1.459, 6.894]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2052.geometry}
                material={materials["Allah (1) - 2018.121"]}
                position={[13.185, 1.459, 4.894]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2053.geometry}
                material={materials["Allah (1) - 2018.122"]}
                position={[13.185, 1.459, 2.894]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2054.geometry}
                material={materials["Allah (1) - 2018.123"]}
                position={[13.185, 1.459, 0.894]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2055.geometry}
                material={materials["Allah (1) - 2018.124"]}
                position={[13.185, 1.459, -1.106]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2056.geometry}
                material={materials["Allah (1) - 2018.125"]}
                position={[13.185, 1.459, -3.106]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2057.geometry}
                material={materials["Allah (1) - 2018.126"]}
                position={[13.185, 1.459, -5.106]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Image_2058.geometry}
                material={materials["Allah (1) - 2018.127"]}
                position={[13.185, 1.459, -7.106]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={1.311}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022"].geometry}
                material={materials["1. Lian - 2022"]}
                position={[-17.634, 4.108, 6.916]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022001"].geometry}
                material={materials["1. Lian - 2022.001"]}
                position={[-17.634, 2.907, 6.916]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022002"].geometry}
                material={materials["1. Lian - 2022.002"]}
                position={[-17.634, 1.681, 6.916]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022003"].geometry}
                material={materials["1. Lian - 2022.003"]}
                position={[-17.634, 1.681, 5.683]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022004"].geometry}
                material={materials["1. Lian - 2022.004"]}
                position={[-17.634, 2.907, 5.683]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022005"].geometry}
                material={materials["1. Lian - 2022.005"]}
                position={[-17.634, 4.108, 5.683]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022006"].geometry}
                material={materials["1. Lian - 2022.006"]}
                position={[-17.634, 4.108, 3.216]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022007"].geometry}
                material={materials["1. Lian - 2022.007"]}
                position={[-17.634, 2.907, 3.216]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022008"].geometry}
                material={materials["1. Lian - 2022.008"]}
                position={[-17.634, 1.681, 3.216]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022009"].geometry}
                material={materials["1. Lian - 2022.009"]}
                position={[-17.634, 1.681, 4.45]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022010"].geometry}
                material={materials["1. Lian - 2022.010"]}
                position={[-17.634, 2.907, 4.45]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022011"].geometry}
                material={materials["1. Lian - 2022.011"]}
                position={[-17.634, 4.108, 4.45]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022012"].geometry}
                material={materials["1. Lian - 2022.012"]}
                position={[-17.634, 4.108, -0.522]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022013"].geometry}
                material={materials["1. Lian - 2022.013"]}
                position={[-17.634, 2.907, -0.522]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022014"].geometry}
                material={materials["1. Lian - 2022.014"]}
                position={[-17.634, 1.681, -0.522]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022015"].geometry}
                material={materials["1. Lian - 2022.015"]}
                position={[-17.634, 1.681, -1.756]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022016"].geometry}
                material={materials["1. Lian - 2022.016"]}
                position={[-17.634, 2.907, -1.756]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022017"].geometry}
                material={materials["1. Lian - 2022.017"]}
                position={[-17.634, 4.108, -1.756]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022018"].geometry}
                material={materials["1. Lian - 2022.018"]}
                position={[-17.634, 4.108, 0.711]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022019"].geometry}
                material={materials["1. Lian - 2022.019"]}
                position={[-17.634, 2.907, 0.711]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022020"].geometry}
                material={materials["1. Lian - 2022.020"]}
                position={[-17.634, 1.681, 0.711]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022021"].geometry}
                material={materials["1. Lian - 2022.021"]}
                position={[-17.634, 1.681, 1.945]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022022"].geometry}
                material={materials["1. Lian - 2022.022"]}
                position={[-17.634, 2.907, 1.945]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022023"].geometry}
                material={materials["1. Lian - 2022.023"]}
                position={[-17.634, 4.108, 1.945]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022027"].geometry}
                material={materials["1. Lian - 2022.027"]}
                position={[-17.634, 1.681, -3.032]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022028"].geometry}
                material={materials["1. Lian - 2022.028"]}
                position={[-17.634, 2.907, -3.032]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022029"].geometry}
                material={materials["1. Lian - 2022.029"]}
                position={[-17.634, 4.108, -3.032]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube007.geometry}
                material={materials["Material.007"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Commercial_Title_Design.geometry}
                material={materials["Material.005"]}
                position={[-17.611, 5.127, 4.731]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.369}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022024"].geometry}
                material={materials["1. Lian - 2022.057"]}
                position={[-1.057, 3.681, 4.597]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022025"].geometry}
                material={materials["1. Lian - 2022.058"]}
                position={[-1.057, 2.473, 4.597]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022026"].geometry}
                material={materials["1. Lian - 2022.059"]}
                position={[-1.057, 1.273, 4.597]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022030"].geometry}
                material={materials["1. Lian - 2022.060"]}
                position={[-1.057, 1.273, 3.369]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022031"].geometry}
                material={materials["1. Lian - 2022.061"]}
                position={[-1.057, 2.473, 3.369]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022032"].geometry}
                material={materials["1. Lian - 2022.062"]}
                position={[-1.057, 3.681, 3.369]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022033"].geometry}
                material={materials["1. Lian - 2022.063"]}
                position={[-1.057, 3.681, 0.908]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022034"].geometry}
                material={materials["1. Lian - 2022.064"]}
                position={[-1.057, 2.473, 0.908]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022035"].geometry}
                material={materials["1. Lian - 2022.065"]}
                position={[-1.057, 1.273, 0.908]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022036"].geometry}
                material={materials["1. Lian - 2022.066"]}
                position={[-1.057, 1.273, 2.136]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022037"].geometry}
                material={materials["1. Lian - 2022.067"]}
                position={[-1.057, 2.473, 2.136]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022038"].geometry}
                material={materials["1. Lian - 2022.068"]}
                position={[-1.057, 3.681, 2.136]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022039"].geometry}
                material={materials["1. Lian - 2022.069"]}
                position={[-1.057, 3.681, -2.808]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022040"].geometry}
                material={materials["1. Lian - 2022.070"]}
                position={[-1.057, 2.473, -2.808]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022041"].geometry}
                material={materials["1. Lian - 2022.071"]}
                position={[-1.057, 1.273, -2.808]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022042"].geometry}
                material={materials["1. Lian - 2022.072"]}
                position={[-1.057, 1.273, -4.036]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022043"].geometry}
                material={materials["1. Lian - 2022.073"]}
                position={[-1.057, 2.473, -4.036]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022044"].geometry}
                material={materials["1. Lian - 2022.074"]}
                position={[-1.057, 3.681, -4.036]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022045"].geometry}
                material={materials["1. Lian - 2022.075"]}
                position={[-1.057, 3.681, -1.576]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022046"].geometry}
                material={materials["1. Lian - 2022.076"]}
                position={[-1.057, 2.473, -1.576]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022047"].geometry}
                material={materials["1. Lian - 2022.077"]}
                position={[-1.057, 1.273, -1.576]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022048"].geometry}
                material={materials["1. Lian - 2022.078"]}
                position={[-1.057, 1.273, -0.348]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022049"].geometry}
                material={materials["1. Lian - 2022.079"]}
                position={[-1.057, 2.473, -0.348]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022050"].geometry}
                material={materials["1. Lian - 2022.080"]}
                position={[-1.057, 3.681, -0.348]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022051"].geometry}
                material={materials["1. Lian - 2022.081"]}
                position={[-1.057, 3.681, -5.31]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022052"].geometry}
                material={materials["1. Lian - 2022.082"]}
                position={[-1.057, 2.473, -5.31]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Lian_-_2022053"].geometry}
                material={materials["1. Lian - 2022.083"]}
                position={[-1.057, 1.273, -5.31]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.093}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_Baked.geometry}
                material={materials.Material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Middle_Stand001_Baked.geometry}
                material={materials.FinalBake_Baked}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Main_Building_Baked001.geometry}
                material={materials.Walls}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Left_Wall001_Baked.geometry}
                material={materials["Alisa final Bake1_Baked"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall001_Baked.geometry}
                material={materials["Alisa final Bake1_Baked"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Main_Building_Baked_Baked.geometry}
                material={materials["Alisa final Bake1_Baked"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall_Baked_Baked.geometry}
                material={materials["Alisa final Bake1_Baked"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall002_Baked_Baked.geometry}
                material={materials["Alisa final Bake1_Baked"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials.Walls}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_1.geometry}
                material={materials.Floor}
            />
        </group>);
}

useGLTF.preload("/thisistheend.glb");
